// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendGymStar.Data
{
    public partial class Caja
    {
        public Caja()
        {
            DetalleCaja = new HashSet<DetalleCaja>();
        }

        public int Cajaid { get; set; }
        public DateTime CajafechaApertura { get; set; }
        public DateTime? CajafechaCierre { get; set; }
        public double CajamontoApertura { get; set; }
        public double? CajamontoCierre { get; set; }
        public DateTime CajafecReg { get; set; }
        public int CajausrReg { get; set; }
        public long GymId { get; set; }
        public long EstId { get; set; }
        public double CajamontoActual { get; set; }

        public virtual Estatus Est { get; set; }
        public virtual Gimnasio Gym { get; set; }
        public virtual ICollection<DetalleCaja> DetalleCaja { get; set; }
    }
}