// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendGymStar.Data
{
    public partial class Clase
    {
        public int Clasid { get; set; }
        public string Clasnombre { get; set; }
        public string Clasdescripcion { get; set; }
        public long EstId { get; set; }
        public double Clasprecio { get; set; }
        public DateTime ClasfecReg { get; set; }
        public int ClasusrReg { get; set; }
        public long GymId { get; set; }

        public virtual Estatus Est { get; set; }
        public virtual Gimnasio Gym { get; set; }
    }
}