// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendGymStar.Data
{
    public partial class ConceptoPago
    {
        public ConceptoPago()
        {
            Pago = new HashSet<Pago>();
        }

        public int Concepid { get; set; }
        public string Concepnombre { get; set; }
        public string Concepdescripcion { get; set; }

        public virtual ICollection<Pago> Pago { get; set; }
    }
}