// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendGymStar.Data
{
    public partial class DetalleCaja
    {
        public int Detcajaid { get; set; }
        public int CajaId { get; set; }
        public int PagoId { get; set; }

        public virtual Caja Caja { get; set; }
        public virtual Pago Pago { get; set; }
    }
}