// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendGymStar.Data
{
    public partial class Estatus
    {
        public Estatus()
        {
            Caja = new HashSet<Caja>();
            Clase = new HashSet<Clase>();
            Gimnasio = new HashSet<Gimnasio>();
            Membresia = new HashSet<Membresia>();
            MembresiaSocio = new HashSet<MembresiaSocio>();
            Producto = new HashSet<Producto>();
            Usuario = new HashSet<Usuario>();
        }

        public long Estid { get; set; }
        public string Estclave { get; set; }
        public string Estdescripcion { get; set; }
        public string Estcategoria { get; set; }

        public virtual ICollection<Caja> Caja { get; set; }
        public virtual ICollection<Clase> Clase { get; set; }
        public virtual ICollection<Gimnasio> Gimnasio { get; set; }
        public virtual ICollection<Membresia> Membresia { get; set; }
        public virtual ICollection<MembresiaSocio> MembresiaSocio { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}