// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendGymStar.Data
{
    public partial class Gimnasio
    {
        public Gimnasio()
        {
            Caja = new HashSet<Caja>();
            Clase = new HashSet<Clase>();
            Membresia = new HashSet<Membresia>();
            Pago = new HashSet<Pago>();
            Producto = new HashSet<Producto>();
            Usuario = new HashSet<Usuario>();
        }

        public long Gymid { get; set; }
        public string Gymnombre { get; set; }
        public string Gymdireccion { get; set; }
        public string Gymlogo { get; set; }
        public string Gymemail { get; set; }
        public string Gymtelefono { get; set; }
        public string GymsitioWeb { get; set; }
        public DateTime GymfecReg { get; set; }
        public bool Gymactivo { get; set; }
        public long EstId { get; set; }

        public virtual Estatus Est { get; set; }
        public virtual ICollection<Caja> Caja { get; set; }
        public virtual ICollection<Clase> Clase { get; set; }
        public virtual ICollection<Membresia> Membresia { get; set; }
        public virtual ICollection<Pago> Pago { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}