// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendGymStar.Data
{
    public partial class MembresiaSocio
    {
        public MembresiaSocio()
        {
            Socio = new HashSet<Socio>();
        }

        public int Memsocid { get; set; }
        public int MembresiaId { get; set; }
        public DateTime FechaRegistro { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaPago { get; set; }
        public long EstId { get; set; }
        public int DiasRestantes { get; set; }

        public virtual Estatus Est { get; set; }
        public virtual Membresia Membresia { get; set; }
        public virtual ICollection<Socio> Socio { get; set; }
    }
}