// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendGymStar.Data
{
    public partial class Pago
    {
        public Pago()
        {
            DetalleCaja = new HashSet<DetalleCaja>();
            DetallePago = new HashSet<DetallePago>();
        }

        public int Pagoid { get; set; }
        public string Descripcion { get; set; }
        public double Total { get; set; }
        public int? UsuarioId { get; set; }
        public int ConceptoId { get; set; }
        public int UsrReg { get; set; }
        public DateTime FechaPago { get; set; }
        public TimeSpan HoraPago { get; set; }
        public string Referencia { get; set; }
        public long Gymid { get; set; }

        public virtual ConceptoPago Concepto { get; set; }
        public virtual Gimnasio Gym { get; set; }
        public virtual ICollection<DetalleCaja> DetalleCaja { get; set; }
        public virtual ICollection<DetallePago> DetallePago { get; set; }
    }
}