// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendGymStar.Data
{
    public partial class Producto
    {
        public int Prodid { get; set; }
        public string Prodnombre { get; set; }
        public string Prodfoto { get; set; }
        public int Prodstock { get; set; }
        public double Prodprecio { get; set; }
        public string Proddetalles { get; set; }
        public long GymId { get; set; }
        public string ProdcodBarras { get; set; }
        public DateTime ProdfecActu { get; set; }
        public DateTime ProdusrActu { get; set; }
        public long? EstId { get; set; }

        public virtual Estatus Est { get; set; }
        public virtual Gimnasio Gym { get; set; }
    }
}