// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendGymStar.Data
{
    public partial class Rol
    {
        public Rol()
        {
            Usuario = new HashSet<Usuario>();
        }

        public long Rolid { get; set; }
        public string Rolclave { get; set; }
        public string Rolnombre { get; set; }

        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}